### ISSUE TITLE
[Dual Screen Expansion] When the expansion screen is on and the main screen is down, the power management window is displayed abnormally

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-power-manager#12]
![2020-04-04 19-57-21屏幕截图](https://user-images.githubusercontent.com/48200161/78450081-94bca700-76ae-11ea-8451-3453f81adea1.png)

**Comment by wyqhnr** [comment]
it was solved now

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
