### ISSUE TITLE
Power and battery powered, change to sleep after 10 minutes, no matter you use power or battery, the system will not go to sleep

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-power-manager#14]

**Comment by wyqhnr** [comment]
it enters into suspend,when pressing on the keyboard,it can be waked up. from this point, it was not an issue. 
problem is that it is not saving power in suspend as expected.

**Comment by Liang-zy** [comment]
Wrong sleep time. The power is set to go to sleep after 10 minutes. Does it mean that it will go to sleep without operating the computer within 10 minutes, or will it go to sleep 10 minutes after entering the lock screen? No matter what the situation is, the system will not go to sleep at the specified time

**Comment by wyqhnr** [comment]
When the idle time is up, the screen will be locked. By default, the idle time is 5 minutes, so the screen will be locked after 5 minutes

Set 10 minutes to go to sleep. It means that after 5 minutes of idle time, start to count for 10 minutes. Once the time is up, the computer is suspended. So setting 10 minutes is equal to the total 15 minutes.

You can also change the suspend to sleep. Whether it can be executed successfully depends on whether the interface provided by the system can be executed successfully. This is beyond the scope of this program。

**Comment by Liang-zy** [comment]
When using battery powerd, enter the screen saver and wait for a while, the screen will become black. After locking the screen for 10 minutes, the screen will automatically wake up without going to sleep.

**Comment by Liang-zy** [comment]
20200611 test passed
