### ISSUE TITLE
The laptop screen auto always back to dim

### ISSUE THREAD

**Issue by brsvh** [ukui/ukui-power-manager#22]
version: launchpad ppa latest build
machine: all laptop devices
arch: amd64

The laptop screen auto alwasy back to dim.

![image](https://user-images.githubusercontent.com/63050399/88379149-f8412080-cdd4-11ea-8467-bc0f25323a13.png)

issue from [telegram Ubuntu Kylin group](https://t.me/ubuntukylin).
reporter:

* Ibnu Fachrizal @ ibnufachrizal
* Allan Pineda @ Alef01

related discussion:

* https://t.me/ubuntukylin/858
* https://t.me/ubuntukylin/987

**Comment by wyqhnr** [comment]
this point is removed now
