### ISSUE TITLE
The power status of the Bluetooth mouse is not displayed

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-power-manager#6]
未显示蓝牙鼠标的电源情况

**Comment by wyqhnr** [comment]
it seems to support those devices that has dbus message to upower daemon.

**Comment by wyqhnr** [comment]
cd /sys/class/power_supply/     to see if there is a node for your bluetooth mouse.

Only when there is a corresponding file node directory in the directory can the power of this Bluetooth device be displayed

**Comment by wyqhnr** [comment]
generally ,this directory contains ac and battery these two kind .when a bluetooth device is connected, a third directory is created.

**Comment by liumin0322** [comment]
待商业版本测试
