### ISSUE TITLE
当电量为5%时，预计剩余时间显示为：放电（5%）

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-power-manager#7]
When the power is 5%, the estimated remaining time is displayed as: discharge (5%)

**Comment by wyqhnr** [comment]
when we cant get the time_to_empty value,we display the message above instead of making it emtpy

**Comment by wyqhnr** [comment]
when we cant get the time_to_empty value,we display the message above instead of making it emtpy.
if in this case ,this is acceptable

**Comment by liumin0322** [comment]
20200309版本测试通过
